CREATE DATABASE ASSET_MANAGEMENT;

USE ASSET_MANAGEMENT;

CREATE TABLE EMPLOYEE (
	eid INT AUTO_INCREMENT PRIMARY KEY,
    ename VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    gender ENUM('FEMALE', 'MALE'),
    contact_number VARCHAR(20),
    address VARCHAR(255),
    role ENUM('EMPLOYEE', 'ADMIN') DEFAULT 'EMPLOYEE'
);

CREATE TABLE ASSET (
	aid INT AUTO_INCREMENT PRIMARY KEY,
    asset_no VARCHAR(50) NOT NULL UNIQUE,
    aname VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    model VARCHAR(50),
    manufacturing_date DATE,
    expiry_date DATE,
    asset_value DECIMAL(10,2),
    status ENUM('AVAILABLE', 'ASSIGNED', 'UNDER_SERVICE') DEFAULT 'AVAILABLE'
);

CREATE TABLE ASSET_ALLOCATION (
	alloc_id INT AUTO_INCREMENT PRIMARY KEY,
    eid INT,
    aid INT,
    allocation_date DATE,
    return_date DATE,
    FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid),
    FOREIGN KEY (aid) REFERENCES ASSET(aid)
);

CREATE TABLE SERVICE_REQUEST (
	srid INT AUTO_INCREMENT PRIMARY KEY,
    eid INT,
    aid INT,
    description TEXT,
    issue_type ENUM('MALFUNCTION', 'REPAIR') NOT NULL,
    status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED'),
    FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid),
    FOREIGN KEY (aid) REFERENCES ASSET(aid)
);

CREATE TABLE AUDIT_REQUEST (
	arid INT AUTO_INCREMENT PRIMARY KEY,
    eid INT,
    aid INT,
    status ENUM('PENDING', 'VERIFIED', 'REJECTED'),
    FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid),
    FOREIGN KEY (aid) REFERENCES ASSET(aid)
);
